title: "" # Title at top of first page
weekstart: 1
ampmtime: false
dotted: false
calafterschedule: false
calafterschedulehidemonth: false  # When true, hides month heading in daily page mini calendar
showkeyonyearpage: false
dailyreflectshowlocationuploaded: false
addlasthalfhour: true

layout:
  paper:
    width: 15.6cm
    height: 20.9cm

    marginparwidth: 1cm
    marginparsep: 0cm
    reversemargins: true

    margin:
      top: 1.2cm
      bottom: 0.7cm
      left: 0.5cm
      right: 0.5cm

  numbers:
    arraystretch: 1.5
    quarterlylines: 36
    weeklylines: 11
    dailytodos: 8
    dailynotes: 25
    dailypersonal: 6
    dailybottomhour: 7
    dailytophour: 23
    dailydiarygoals: 10
    dailydiarygrateful: 4
    dailydiarybest: 4
    dailydiarylog: 24
    todolinesintodopage: 10
    notesindexpages: 3
    notesonpage: 35
    dotheightfull: 36
    dotwidthfull: 30
    dotwidthtwothirds: 20
    dailyreflectextra: 6  # Number of additional reflect pages per day


  lengths:
    tabcolsep: 3.5pt
    linethicknessdefault: .4pt
    linethicknessthick: .8pt
    lineheightbutline: \dimexpr5mm-.4pt
    twocolsep: 5pt
    tricolsep: 5pt
    fivecolsep: 5pt
    monthlycellheight: 55pt
    notesindexcellheight: 1.37cm
    headerresizebox: 6mm
    headersidequarterswidth: 4cm
    headersidemonthswidth: 14.5cm
    dailyspring: \textcolor{white}{.}

  colors:
    gray: gray!90
    lightgray: gray!60