// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/kudrykv/latex-yearly-planner/internal/core/planners/entities"
	mock "github.com/stretchr/testify/mock"
)

// FileWriter is an autogenerated mock type for the FileWriter type
type FileWriter struct {
	mock.Mock
}

// Write provides a mock function with given fields: _a0, _a1
func (_m *FileWriter) Write(_a0 context.Context, _a1 entities.File) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.File) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewFileWriter interface {
	mock.TestingT
	Cleanup(func())
}

// NewFileWriter creates a new instance of FileWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFileWriter(t mockConstructorTestingTNewFileWriter) *FileWriter {
	mock := &FileWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
