AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'sweep-away/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
