version: '0.1'

template: mos

compiler:
  ghostscript:
    enable: true

document:
  layout:
    dimensions:
      width: 158mm
      height: 210mm

    margin:
      top: 10mm
      bottom: 0mm
      left: 5mm
      right: 0mm

  text:
    size: 10pt

planner:
  params:
    start_date: "2026-01-01"
    end_date: "2026-12-31"
    weekday_start: Monday

    heading:
      height: 10mm
      title_font_size: 10mm
      align: horizon

    mos_layout:
      side_menu_position: right
      side_menu_width: 10mm

  sections:
    - name: title
      enabled: false
      params:
        name: "2026\n\nPlanner"
        font_size: 48pt

    - name: weekly
      enabled: true
      params:
        hello: world