#!/usr/bin/env ruby
# frozen_string_literal: true

# noinspection RubyMismatchedArgumentType
lib_path = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)

require "latex_yearly_planner/cli"

LatexYearlyPlanner::CLI.start(ARGV)
